In [ ]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [4]:
np.empty([2,2], int)

array([[0, 0],
       [0, 0]])

Let A = np.array([1,2,3], [4,5,6], np.int32). Create a new array with the same shape and type as A.

In [6]:
A = np.array([[1,2,3], [4,5,6]], np.int32)

In [7]:
np.empty_like(A)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [8]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])


Create a new array of 3*2 float numbers, filled with ones.

In [9]:
np.ones([3,2], float)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [10]:
x = np.arange(4, dtype=np.int64)

In [12]:
np.zeros_like(x)

array([0, 0, 0, 0])