In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.1'

## Trigonometry

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [3]:
x = np.array([0., 1., 30, 90])

In [11]:
print 'sine: ', np.sin(x)
print 'cosine: ', np.cos(x)
print 'tangent: ', np.tan(x)

sine:  [ 0.          0.84147098 -0.98803162  0.89399666]
cosine:  [ 1.          0.54030231  0.15425145 -0.44807362]
tangent:  [ 0.          1.55740772 -6.4053312  -1.99520041]


Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [12]:
x = np.array([-1., 0, 1.])

In [14]:
print "inverse sine:", np.arcsin(x)
print "inverse cosine:", np.arccos(x)
print "inverse tangent:", np.arctan(x)

 inverse sine: [-1.57079633  0.          1.57079633]
inverse cosine: [ 3.14159265  1.57079633  0.        ]
inverse tangent: [-0.78539816  0.          0.78539816]


Q3. Convert angles from radians to degrees.

In [15]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

In [16]:
out1 = np.degrees(x)
out2 = np.rad2deg(x)
assert np.array_equiv(out1, out2)
print out1

[-180.  -90.   90.  180.]


Q4. Convert angles from degrees to radians.

In [17]:
x = np.array([-180.,  -90.,   90.,  180.])

In [18]:
out1 = np.radians(x)
out2 = np.deg2rad(x)
assert np.array_equiv(out1, out2)
print out1

[-3.14159265 -1.57079633  1.57079633  3.14159265]


## Hyperbolic functions

Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [19]:
x = np.array([-1., 0, 1.])

In [20]:
print np.sinh(x)
print np.cosh(x)
print np.tanh(x)

[-1.17520119  0.          1.17520119]
[ 1.54308063  1.          1.54308063]
[-0.76159416  0.          0.76159416]


## Exponents and logarithms

Q6. Compute $e^x$, element-wise.

In [21]:
x = np.array([1., 2., 3.], np.float32)

In [22]:
print np.exp(x)

[  2.71828175   7.38905621  20.08553696]


Q7. Calculate exp(x) - 1 for all elements in x.

In [23]:
x = np.array([1., 2., 3.], np.float32)

In [24]:
out1 = np.expm1(x)
out2 = np.exp(x) - 1.
assert np.allclose(out1, out2)
print out1

[  1.71828175   6.38905621  19.08553696]


Q8. Calculate $2^p$ for all p in x.

In [26]:
x = np.array([1., 2., 3.], np.float32)

In [27]:
out1 = np.exp2(x)
out2 = 2 ** x
assert np.allclose(out1, out2)
print out1

[ 2.  4.  8.]
